"""guess

Revision ID: 699d25f66dcd
Revises: bd5be0a365e3
Create Date: 2022-11-26 13:37:24.705897

"""
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision = '699d25f66dcd'
down_revision = 'bd5be0a365e3'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('guesses',
                    sa.Column('identifier', postgresql.UUID(
                        as_uuid=True), nullable=False),
                    sa.Column('game_id', postgresql.UUID(
                        as_uuid=True), nullable=True),
                    sa.Column('code', sa.String(length=4), nullable=True),
                    sa.Column('black_peqs', sa.Integer(), nullable=True),
                    sa.Column('white_peqs', sa.Integer(), nullable=True),
                    sa.Column('guessed', sa.Boolean(), nullable=True),
                    sa.Column('date_created', sa.DateTime(timezone=True),
                              server_default=sa.text('now()'), nullable=True),
                    sa.ForeignKeyConstraint(
                        ['game_id'], ['games.identifier'], ),
                    sa.PrimaryKeyConstraint('identifier')
                    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('guesses')
    # ### end Alembic commands ###
