"""remove_guessed

Revision ID: 9b1c372e8966
Revises: 699d25f66dcd
Create Date: 2022-11-26 13:38:59.974681

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = '9b1c372e8966'
down_revision = '699d25f66dcd'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('guesses', 'guessed')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('guesses', sa.Column('guessed', sa.BOOLEAN(),
                  autoincrement=False, nullable=True))
    # ### end Alembic commands ###
