"""game

Revision ID: bd5be0a365e3
Revises: 
Create Date: 2022-11-25 16:17:22.170866

"""
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision = 'bd5be0a365e3'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('games',
                    sa.Column('identifier', postgresql.UUID(
                        as_uuid=True), nullable=False),
                    sa.Column('code', sa.String(length=4), nullable=True),
                    sa.Column('max_tries', sa.Integer(), nullable=True),
                    sa.Column('tries', sa.Integer(), nullable=True),
                    sa.Column('guessed', sa.Boolean(), nullable=True),
                    sa.Column('date_created', sa.DateTime(timezone=True),
                              server_default=sa.text('now()'), nullable=True),
                    sa.Column('date_modified', sa.DateTime(
                        timezone=True), nullable=True),
                    sa.PrimaryKeyConstraint('identifier')
                    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('games')
    # ### end Alembic commands ###
